# Generated by Django 5.2.7 on 2025-10-17 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onchain_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_address', models.CharField(max_length=42)),
                ('chain', models.CharField(default='arbitrum_one', max_length=32)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('raw_amount', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('FUNDED', 'Funded'), ('SHIPPED', 'Shipped'), ('COMPLETE', 'Complete'), ('DISPUTE', 'Dispute'), ('REFUNDED', 'Refunded')], default='AWAITING_PAYMENT', max_length=20)),
                ('tx_create', models.CharField(blank=True, max_length=100, null=True)),
                ('tx_fund', models.CharField(blank=True, max_length=100, null=True)),
                ('tx_release', models.CharField(blank=True, max_length=100, null=True)),
                ('tx_refund', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('evidence', models.JSONField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('escrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='marketplace.escrow')),
            ],
        ),
        migrations.CreateModel(
            name='EscrowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('block_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='marketplace.escrow')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=18, max_digits=36)),
                ('token_address', models.CharField(blank=True, max_length=42, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='escrow',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.listing'),
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.listing')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('escrow', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.escrow')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seller', models.BooleanField(default=False)),
                ('wallet_address', models.CharField(blank=True, max_length=42, null=True)),
                ('category', models.CharField(blank=True, choices=[('gadgets', 'Gadgets'), ('fashion', 'Fashion'), ('sports', 'Sports'), ('books', 'Books'), ('home', 'Home'), ('other', 'Other')], max_length=50, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('farcaster_fid', models.CharField(blank=True, max_length=128, null=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['onchain_id'], name='marketplace_onchain_69327f_idx'),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['contract_address'], name='marketplace_contrac_9af9d7_idx'),
        ),
    ]
