# Generated by Django 5.2.7 on 2025-10-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_profile_avatar_url_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escrowevent',
            name='event_type',
            field=models.CharField(choices=[('payment_secured', 'Payment Secured'), ('item_shipped', 'Item Shipped'), ('delivered', 'Item Delivered'), ('released', 'Funds Released'), ('refunded', 'Funds Refunded'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved')], default='payment_secured', max_length=50),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
