# Generated by Django 5.2.7 on 2025-10-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_escrowevent_description_alter_escrowevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved')], default='dispute_opened', max_length=20),
        ),
    ]
